# --------------------------------------------------
# 01. Pandas Basics
# --------------------------------------------------

In [ ]:
# Pandas is a python library mainly used for working with tabular data.
import pandas as pd     # importing pandas library and giving it an alias name 'pd'

# Series is basically a 1- dimensional array that can hold any data type.
marks = pd.Series([85, 90, 78, 92])     # pd.series(data)
print(marks)                            # printing the series

# we can also give our own labels to the series.
marks = pd.Series(
    [85, 90, 78],
    index=["Rahul", "Aman", "Priya"]
)
print(marks)

# accessing the data in series using index labels
print(marks["Rahul"])    # accessing data for Rahul
        
print(marks[0])         # accessing data for Rahul using index position
print(marks.mean())     # calculating the mean of the series
print(marks.max())      # calculating the maximum value of the series
print(marks.min())      # calculating the minimum value of the series
print(marks.describe())  # getting the statistical summary of the series, it includes count, mean, std, min, 25%, 50%, 75%, max values of the series

0    85
1    90
2    78
3    92
dtype: int64
Rahul    85
Aman     90
Priya    78
dtype: int64
85
85
84.33333333333333
90
78
count     3.000000
mean     84.333333
std       6.027714
min      78.000000
25%      81.500000
50%      85.000000
75%      87.500000
max      90.000000
dtype: float64

C:\Users\hp\AppData\Local\Temp\ipykernel_22724\3118568246.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])         # accessing data for Rahul using index position

# --------------------------------------------------
# 02. Dataframe
# --------------------------------------------------

In [11]:
# A DataFrame is a 2-dimentional array (table) made up of rows and columns. It is similar to a spreadsheet or SQL table.
data = {                                    
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}                                           # creating a dataframe using a dictionary where keys are column names and values are lists of column data
df = pd.DataFrame(data)                     # creating a dataframe using pd.DataFrame(data)
print(df)                                   # printing the dataframe

print(type(df))                             # printing the type of the dataframe

# selecting a column from the dataframe
print(df["Name"])                           # selecting the 'Name' column from the dataframe
print(df[["Name", "Marks"]])                # selecting multiple columns from the dataframe
print(df.loc[0])                            # selecting a row from the dataframe using index position
print(df.iloc[0])                           # selecting a row from the dataframe using index label
print(df.loc[0, "Name"])                     # selecting a specific value from the dataframe using index position and column name

    Name  Age  Marks
0  Rahul   21     85
1   Aman   22     90
2  Priya   20     78
<class 'pandas.core.frame.DataFrame'>
0    Rahul
1     Aman
2    Priya
Name: Name, dtype: object
    Name  Marks
0  Rahul     85
1   Aman     90
2  Priya     78
Name     Rahul
Age         21
Marks       85
Name: 0, dtype: object
Name     Rahul
Age         21
Marks       85
Name: 0, dtype: object
Rahul

# --------------------------------------------------
# 03. Loading real data with pandas
# --------------------------------------------------

In [20]:
df = pd.read_csv("students.csv")        # reading a csv file and creating a dataframe from it
print(df)                               # printing the dataframe

df.head()                               # printing the first 5 rows of the dataframe
df.head(3)                              # printing the first 3 rows of the dataframe
df.tail()                               # printing the last 5 rows of the dataframe
df.tail(3)                              # printing the last 3 rows of the dataframe

# only the latest function will be executed, so if you want to see the output of all the above functions, you need to print them.

df.shape                                  # printing the shape of the dataframe (number of rows, number of columns)
df.columns                                # printing the column names of the dataframe
df.info()                                 # printing the information about the dataframe (number of non-null values, data types of columns)
df.describe()                             # printing the statistical summary of the dataframe (count, mean, std, min, 25%, 50%, 75%, max values of the numerical columns)

    Name  Age  Marks       City
0  Rahul   21     85      Delhi
1   Aman   22     90      Noida
2  Priya   20     78  Ghaziabad
3   Riya   21     92      Delhi
4  Karan   22     67      Noida
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

            Age      Marks
count   5.00000   5.000000
mean   21.20000  82.400000
std     0.83666  10.163661
min    20.00000  67.000000
25%    21.00000  78.000000
50%    21.00000  85.000000
75%    22.00000  90.000000
max    22.00000  92.000000

# --------------------------------------------------
# 04. Selecting Rows and Columns
# --------------------------------------------------

In [22]:
df["Name"]                # select a comumn
df[["Name", "Marks"]]     # select multiple columns

# selecting using iloc
# iloc is used to select rows and columns by their integer index positions.

df.iloc[0]                # selecting the first row of the dataframe
df.iloc[0, 0]             # selecting the first row and first column of the
df.iloc[0:3]              # selecting the first 3 rows of the dataframe
df.iloc[0:3, 0:2]         # selecting the first 3 rows and first 2 columns of the dataframe
df.iloc[0:3, 2:4]         # selecting the first 3 rows and last 2 columns of the dataframe
# latest function will be executed, so if you want to see the output of all the above functions, you need to print them.

# select rows and columns with a condition
df[df["Marks"] > 80]      # selecting rows where the 'Marks' column
df[df["City"] == "Delhi"] # selecting rows where the 'City' column is equal to 'Delhi'

    Name  Age  Marks   City
0  Rahul   21     85  Delhi
3   Riya   21     92  Delhi

# --------------------------------------------------
# 05. Missing Data — Handling (NaN)
# --------------------------------------------------

In [ ]:
# Real world dataframe often have missing values
#| Name  | Age | Marks |
#| ----- | --: | ----: |
#| Rahul |  21 |    85 |
#| Aman  | NaN |    90 |
#| Priya |  20 |   NaN |

df_test = df.copy()             # creating a copy of the dataframe to demonstrate missing values
df_test.loc[1, "Age"] = None    # setting the value of the 'Age' column for the second row to None (missing value)
df_test.loc[2, "Marks"] = None  # setting the value of the 'Marks' column for the third row to None (missing value)
print(df_test)                  # displaying the dataframe with missing values

df_test.isnull()                # checking for missing values in the dataframe, it will return a dataframe of the same shape with True for missing values and False for non-missing values
df_test.isnull().sum()          # counting the number of missing values in each column of the dataframe

    Name   Age  Marks       City
0  Rahul  21.0   85.0      Delhi
1   Aman   NaN   90.0      Noida
2  Priya  20.0    NaN  Ghaziabad
3   Riya  21.0   92.0      Delhi
4  Karan  22.0   67.0      Noida

    Name    Age  Marks   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False  False
4  False  False  False  False

# --------------------------------------------------
# 06. dropna() — Removing Missing Data/ filna() - Filling Missing Data
# --------------------------------------------------

In [ ]:
# dropna() function is used to remove missing values from the dataframe.
clean_df = df_test.dropna()             # removing rows with missing values from the dataframe, it will return a new dataframe without missing values
print(clean_df)                         # displaying the dataframe after removing rows with missing values
# Aman → Age missing → row removed
# Priya → Marks missing → row removed

# fillna() function is used to fill missing values in the dataframe with a specified value.
df_test.fillna(0)                       # filling missing values in the dataframe with 0
print(df_test.fillna(0))                # displaying the dataframe after filling missing values with 0

    Name   Age  Marks   City
0  Rahul  21.0   85.0  Delhi
3   Riya  21.0   92.0  Delhi
4  Karan  22.0   67.0  Noida
    Name   Age  Marks       City
0  Rahul  21.0   85.0      Delhi
1   Aman   0.0   90.0      Noida
2  Priya  20.0    0.0  Ghaziabad
3   Riya  21.0   92.0      Delhi
4  Karan  22.0   67.0      Noida
    Name   Age  Marks       City
0  Rahul  21.0   85.0      Delhi
1   Aman  21.0   90.0      Noida
2  Priya  20.0   83.5  Ghaziabad
3   Riya  21.0   92.0      Delhi
4  Karan  22.0   67.0      Noida

# --------------------------------------------------
# 07. Sorting & Basic Aggregation
# --------------------------------------------------

In [36]:
# sorting dataframe
print(df.sort_values("Marks"))                     # sorting the dataframe by the 'Marks' column in ascending order
print(df.sort_values("Marks", ascending=False))    # sorting the dataframe by the 'Marks' column in descending order

# value count()
print(df["City"].value_counts())                   # counting the number of occurrences of each unique value in the 'City' column of the dataframe

# basic operations on dataframe
print(df["Marks"].mean())                          # calculating the mean of the 'Marks' column in the dataframe
print(df["Marks"].sum())                           # calculating the sum of the 'Marks' column in the dataframe
print(df["Marks"].max())                           # calculating the maximum value of the 'Marks' column in the dataframe
print(df["Marks"].min())                           # calculating the minimum value of the 'Marks' column in the dataframe
print(df["Marks"].std())                           # calculating the standard deviation of the 'Marks' column in the dataframe

    Name  Age  Marks       City
4  Karan   22     67      Noida
2  Priya   20     78  Ghaziabad
0  Rahul   21     85      Delhi
1   Aman   22     90      Noida
3   Riya   21     92      Delhi
    Name  Age  Marks       City
3   Riya   21     92      Delhi
1   Aman   22     90      Noida
0  Rahul   21     85      Delhi
2  Priya   20     78  Ghaziabad
4  Karan   22     67      Noida
City
Delhi        2
Noida        2
Ghaziabad    1
Name: count, dtype: int64
82.4
412
92
67
10.16366075781753

# --------------------------------------------------
# 8. Data Cleaning — Duplicates & Data Types
# --------------------------------------------------

In [42]:
# checking for duplicates in the dataframe
print(df.duplicated())                             # checking for duplicate rows in the dataframe, it will return a boolean series
print(df.duplicated().sum())                       # counting the number of duplicate rows in the dataframe

# removing duplicates from the dataframe
df.drop_duplicates(inplace=True)                   # removing duplicate rows from the dataframe, it will modify the original dataframe in place

print(df.dtypes)                                   # printing the data types of each column in the dataframe
df["Marks"] = df["Marks"].astype(int)              # converting the data type of the 'Marks' column to integer
df["Age"] = df["Marks"].astype(float)                # converting the data type of the 'Marks' column to float

print(df["Marks"].dtype)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0
Name      object
Age      float64
Marks      int64
City      object
dtype: object
int64